### ISSUE TITLE
Test displaying html files

### ISSUE THREAD

**Issue by WilliamDiakite** [ouvroir/IIIF#25]
Text annotations about Righettino painting are encoded in TEI files. HTML or XML files will be produced based on these and associated to perticular elements of the painting. 
Can we display these html or xml files using svelte ?

**Comment by WilliamDiakite** [comment]
Two ways for loading html or xml files: 

**XMLHttpRequest**
 - returns a Document object directly (parsing made in background)
 - needs a bunch of event liseteners
 - or re-implemlent Promises...

**Fetch API**
- text in response has to be parsed as Document (people had to parse response text as JSON when using XHR),
- works with promises (cleaner code)
- this is the current standard

**Comment by emchateau** [comment]
As far as I know the fetch API doesn’t work with xml files.
There is no native xml parser with the Fetch API. This is not the case with XmlHttpRequest() but this solution reclaim to build a fonction to generate a promise

https://stackoverflow.com/questions/37693982/how-to-fetch-xml-with-fetch-api

Solutions with the fetch API are mostly ugly..


Emmanuel Château
Professeur agrégé
Université de Montréal
@emchateau
