### ISSUE TITLE
Try exhibition and guided tours tools

### ISSUE THREAD

**Issue by WilliamDiakite** [ouvroir/IIIF#5]
- [x] Exhibit Demos
https://www.exhibit.so/exhibits/CLPsiwOep8Ediozzkj1b (template - slides)
https://www.exhibit.so/exhibits/opXpcHLztQJ3RxmDpAXn (template - scroll)
https://www.exhibit.so/exhibits/GIIkF5eKjgNhqMaovfA6 (template - quiz)
https://www.exhibit.so/exhibits/j2H22SJDfIZdYgT7KlSn (template - kiosk)

- [x] Storiiies Demo
https://storiiies.cogapp.com/viewer/ea3d7/Righettino-Image

- [x] Visual Essays Demo
https://visual-essays.app/chaitanyatekane/visualessaytool/chaitanyatekane/visualessaytool/new-page/

- [x] Exihibit, Storiiies and Visual Essays Writings
https://docs.google.com/document/d/1zyGe4FQQgxWUZT9ghUaLZu8X4Sj1Fv9mm2GOXaVW-9M/edit?usp=sharing

**Comment by chaitanyatekane** [comment]
added more information about compliance with IIIF
